git:
  branchPrefix: "gabriel/"
  pager: "diff-so-fancy"
  commit:
    signOff: true
    autoWrapCommitMessage: false
  mainBranches:
    - master
    - main
gui:
  nerdFontsVersion: "3"
  branchColors:
    'master': 'cyan'
    'release': 'yellow'
    'cherry': 'red'
    'ci-': '#777777'
    'auto-': '#777777'
    'backup': '#777777'
    # 'gabriel': 'green'

  authorColors:
    'Gabriel Lanata': 'yellow'
    '*': 'white'
  commandLogSize: 6
  # expandFocusedSidePanel: true
os:
  editPreset: 'vscode'
customCommands:
  - key: 'x'
    description: 'Open in Xcode'
    context: 'global'
    command: 'x {{if .SelectedFile}}./{{.SelectedFile.Name}}{{end}}'
  - key: 'u'
    description: 'Undo last commit'
    context: 'commits'
    prompts:
      - type: 'confirm'
        title: 'Undo last commit'
        body: 'Are you sure you want to undo the last commit?'
    command: 'git reset --soft HEAD~1'
  - key: 'C'
    description: 'Cleanup branches'
    context: 'localBranches'
    prompts:
      - type: 'confirm'
        title: 'Cleanup branches'
        body: 'Are you sure you delete all branches that are merged upstream?'
    command: 'git cleanup -f'
    loadingText: 'Cleaning up branches'
  - key: 'q'
    description: 'Quick commit and PR'
    context: 'global'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Body'
        key: 'Body'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: >-
          {{- if .SelectedLocalBranch.Name -}}
            {{.SelectedLocalBranch.Name}}
          {{- else if .SelectedRemoteBranch.Name -}}
            {{.SelectedRemoteBranch.Name}}
          {{- else -}}
            {{.CheckedOutBranch.Name}}
          {{- end -}}
        suggestions:
          preset: 'branches'
    command: 'prs submit --title "{{.Form.Title}}" --body "{{.Form.Body}}" --base {{.Form.BaseBranch}} -v'
    loadingText: 'Creating Quick PR'
  - key: 'Q'
    description: 'Quick commit and Fixup'
    context: 'global'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: >-
          {{- if .SelectedLocalBranch.Name -}}
            {{.SelectedLocalBranch.Name}}
          {{- else if .SelectedRemoteBranch.Name -}}
            {{.SelectedRemoteBranch.Name}}
          {{- else -}}
            {{.CheckedOutBranch.Name}}
          {{- end -}}
        suggestions:
          preset: 'branches'
    command: 'prs fixup --base {{.Form.BaseBranch}} -v'
    loadingText: 'Creating Quick Fixup'





