promptToReturnFromSubprocess: false
git:
  branchPrefix: 'gabriel/'
  paging:
    pager: 'diff-so-fancy'
  commit:
    signOff: true
    autoWrapCommitMessage: false
  mainBranches:
    - master
    - main
gui:
  nerdFontsVersion: '3'
  branchColors:
    'master': 'cyan'
    'release': 'yellow'
    'cherry': 'red'
    'ci-': '#777777'
    'auto-': '#777777'
    'backup': '#777777'
    # 'gabriel': 'green'
  authorColors:
    'Gabriel Lanata': 'yellow'
    '*': 'white'
  commandLogSize: 6
  filterMode: substring
os:
  editPreset: 'cursor'
keybinding:
  universal:
    quit: '<disabled>'
    quitWithoutChangingDirectory: '<disabled>'
    prevItem-alt: '<disabled>'
    nextItem-alt: '<disabled>'
    prevBlock-alt: '<disabled>'
    nextBlock-alt: '<disabled>'
    scrollLeft: '<disabled>'
    scrollRight: '<disabled>'
    scrollUpMain-alt1: '<disabled>'
    scrollDownMain-alt1: '<disabled>'
    prevBlock: '<disabled>'
    nextBlock:  '<disabled>'
    # return: '<left>'
    # goInto: '<right>'
  files:
    commitChangesWithEditor: '<disabled>'
  commits:
    amendToCommit: 'a'
    resetCommitAuthor: '<disabled>'
    revertCommit: 'r'
    renameCommit: 't'
    renameCommitWithEditor: '<disabled>'
customCommands:
  - key: 'x'
    description: 'Open in Xcode'
    context: 'global'
    command: 'x {{if .SelectedFile}}./{{.SelectedFile.Name}}{{end}}'
  - key: 'q'
    description: 'Quick commit and PR'
    context: 'global'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Body'
        key: 'Body'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: 'master'
        suggestions:
          preset: 'branches'
    command: 'pr submit --title "{{.Form.Title}}" --body "{{.Form.Body}}" --base "{{.Form.BaseBranch}}"'
    loadingText: 'Creating Quick PR'
  - key: 'q'
    description: 'Quick commit and PR'
    context: 'localBranches'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Body'
        key: 'Body'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: >-
          {{- if .SelectedLocalBranch.Name -}}
            {{.SelectedLocalBranch.Name}}
          {{- else if .SelectedRemoteBranch.Name -}}
            {{.SelectedRemoteBranch.Name}}
          {{- else -}}
            {{.CheckedOutBranch.Name}}
          {{- end -}}
        suggestions:
          preset: 'branches'
    command: 'pr submit --title "{{.Form.Title}}" --body "{{.Form.Body}}" --base "{{.Form.BaseBranch}}"'
    loadingText: 'Creating Quick PR'
  - key: 'Q'
    description: 'Quick commit and Fixup'
    context: 'global'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: 'recent'
        suggestions:
          preset: 'branches'
    command: 'pr fixup --base "{{.Form.BaseBranch}}"'
    loadingText: 'Creating Quick Fixup'
  - key: 'Q'
    description: 'Quick commit and Fixup'
    context: 'localBranches'
    stream: true
    prompts:
      - type: 'input'
        title: 'Title'
        key: 'Title'
        initialValue: ''
      - type: 'input'
        title: 'Base branch'
        key: 'BaseBranch'
        initialValue: >-
          {{- if .SelectedLocalBranch.Name -}}
            {{.SelectedLocalBranch.Name}}
          {{- else if .SelectedRemoteBranch.Name -}}
            {{.SelectedRemoteBranch.Name}}
          {{- else -}}
            {{.CheckedOutBranch.Name}}
          {{- end -}}
        suggestions:
          preset: 'branches'
    command: 'pr fixup --base "{{.Form.BaseBranch}}"'
    loadingText: 'Creating Quick Fixup'
  - key: 'l'
    description: 'Lyft generate'
    context: 'global'
    stream: true
    command: 'lyft generate'
    loadingText: 'Generating Lyft project'
  - key: 'L'
    description: 'Lyft generate add module'
    context: 'global'
    stream: true
    prompts:
      - type: 'menuFromCommand'
        title: 'Module:'
        key: 'Module'
        command: 'lyft list-modules'
    command: 'lyft generate {{.Form.Module}}'
    loadingText: 'Generating Lyft project'
  - key: 'u'
    description: 'Undo last commit'
    context: 'global'
    prompts:
      - type: 'confirm'
        title: 'Undo last commit'
        body: 'Are you sure you want to undo the last commit?'
    command: 'git reset --soft HEAD~1'
  - key: 'D'
    description: 'Cleanup branches'
    context: 'localBranches'
    prompts:
      - type: 'confirm'
        title: 'Cleanup branches'
        body: 'Are you sure you delete all branches that are merged upstream?'
    command: 'git cleanup -f'
    loadingText: 'Cleaning up branches'
